import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Use — Clario",
  description: "Terms of Use for Clario, the AI-powered email assistant.",
}

const LAST_UPDATED = "July 5, 2026"

function ClarioMark({ size = 15 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
      <path d="M11.5 1.6c.7 5.7 1.9 6.9 7.6 7.6-5.7.7-6.9 1.9-7.6 7.6-.7-5.7-1.9-6.9-7.6-7.6 5.7-.7 6.9-1.9 7.6-7.6Z" />
      <path d="M18.4 14.2c.35 2.6.95 3.2 3.55 3.55-2.6.35-3.2.95-3.55 3.55-.35-2.6-.95-3.2-3.55-3.55 2.6-.35 3.2-.95 3.55-3.55Z" opacity="0.9" />
    </svg>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-[#1B2735] mb-3">{title}</h2>
      <div className="text-slate-600 leading-relaxed space-y-3">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-primary-50 text-slate-900">
      <header className="border-b border-primary-100 bg-white/70 backdrop-blur-sm">
        <div className="max-w-3xl mx-auto px-6 py-5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-bold text-[#1B2735] text-lg">
            <span className="flex items-center justify-center w-7 h-7 rounded-lg bg-primary-600 text-white shrink-0">
              <ClarioMark size={15} />
            </span>
            Clario
          </Link>
          <Link href="/" className="text-sm text-slate-500 hover:text-primary-700 transition-colors">
            &larr; Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-14">
        <h1 className="text-4xl font-bold text-[#1B2735] mb-2">Terms of Use</h1>
        <p className="text-slate-500 text-sm mb-12">Last updated: {LAST_UPDATED}</p>

        <p className="text-slate-600 leading-relaxed mb-10">
          These Terms of Use (&ldquo;Terms&rdquo;) govern your access to and use of Clario, an
          AI-powered email assistant, including our website, applications, and related services
          (collectively, the &ldquo;Service&rdquo;), provided by Clario AI LLC, a Wyoming limited
          liability company (&ldquo;Clario,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;). By creating an account, connecting an email provider, or otherwise
          using the Service, you agree to be bound by these Terms. If you do not agree, do not use
          the Service.
        </p>

        <Section title="1. Eligibility and Accounts">
          <p>
            You must be at least 16 years old, or the age of digital consent in your jurisdiction,
            to use the Service. You are responsible for maintaining the confidentiality of your
            account credentials and for all activity that occurs under your account. You must
            notify us promptly of any unauthorized use of your account.
          </p>
        </Section>

        <Section title="2. Description of the Service">
          <p>
            Clario connects to third-party email providers (such as Gmail or Outlook) that you
            authorize, and uses artificial intelligence, including large language models, to help
            you search, summarize, draft, and manage your email. Outputs generated by the Service
            are produced automatically and may be inaccurate, incomplete, or inappropriate for a
            given context.
          </p>
          <p>
            You are solely responsible for reviewing any AI-generated content, including draft
            replies and summaries, before relying on it or sending it to a third party. Clario is
            a tool to assist your judgment, not a substitute for it.
          </p>
        </Section>

        <Section title="3. Authorized Use">
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You will not:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Use the Service to send spam, phishing messages, or fraudulent communications;</li>
            <li>Access or attempt to access accounts, data, or systems you are not authorized to access;</li>
            <li>Reverse engineer, decompile, or attempt to extract the underlying models or source code of the Service;</li>
            <li>Use the Service to build a competing product, or to train or fine-tune a competing AI model;</li>
            <li>Interfere with, disrupt, or overburden the Service's infrastructure, including through automated scraping or excessive API requests;</li>
            <li>Upload or transmit content that is unlawful, infringing, defamatory, or that violates the rights of others;</li>
            <li>Circumvent, disable, or otherwise interfere with security-related features of the Service.</li>
          </ul>
          <p>
            We may suspend or terminate your access immediately, without notice, if we reasonably
            believe you have violated this section.
          </p>
        </Section>

        <Section title="4. Connected Accounts and Your Data">
          <p>
            When you connect an email account, you authorize Clario to access your messages on
            your behalf solely to provide the Service to you. You represent that you have the
            right to grant this access, including with respect to any third-party correspondence
            contained in your mailbox.
          </p>
          <p>
            You retain ownership of your email content. You are responsible for complying with any
            confidentiality, privacy, or data-protection obligations that apply to the
            correspondence you process through the Service, including obligations to other people
            who emailed you.
          </p>
        </Section>

        <Section title="5. Acceptable Content">
          <p>
            You are solely responsible for the content of the emails you send, draft, or generate
            using the Service. Clario does not pre-screen content and assumes no responsibility for
            the accuracy, legality, or appropriateness of user-directed communications sent through
            the Service.
          </p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>
            The Service, including its software, design, branding, and underlying technology, is
            owned by Clario and its licensors and is protected by intellectual property laws. These
            Terms do not grant you any right to use our trademarks, logos, or branding without
            prior written permission.
          </p>
        </Section>

        <Section title="7. Disclaimers">
          <p>
            THE SERVICE, INCLUDING ALL AI-GENERATED OUTPUT, IS PROVIDED &ldquo;AS IS&rdquo; AND
            &ldquo;AS AVAILABLE,&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED,
            OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
            PURPOSE, NON-INFRINGEMENT, OR ACCURACY. WE DO NOT WARRANT THAT THE SERVICE WILL BE
            UNINTERRUPTED, SECURE, OR ERROR-FREE, OR THAT AI-GENERATED CONTENT WILL BE ACCURATE OR
            SUITABLE FOR YOUR PURPOSES.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLARIO AND ITS OFFICERS, EMPLOYEES, AND
            LICENSORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
            PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES,
            ARISING OUT OF OR RELATED TO YOUR USE OF, OR INABILITY TO USE, THE SERVICE, INCLUDING
            ANY RELIANCE ON AI-GENERATED CONTENT.
          </p>
          <p>
            OUR TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE
            SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE MONTHS
            PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100).
          </p>
        </Section>

        <Section title="9. Indemnification">
          <p>
            You agree to indemnify, defend, and hold harmless Clario and its officers, employees,
            and licensors from any claims, damages, liabilities, and expenses (including reasonable
            attorneys&rsquo; fees) arising out of your use of the Service, your violation of these
            Terms, or your violation of any rights of a third party, including any content you send
            or generate using the Service.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            You may stop using the Service and disconnect your email account at any time. We may
            suspend or terminate your access to the Service at any time, with or without cause or
            notice, including for violation of these Terms. Upon termination, your right to use the
            Service will immediately cease.
          </p>
        </Section>

        <Section title="11. Modifications to the Service and Terms">
          <p>
            We may modify or discontinue the Service, in whole or in part, at any time. We may
            update these Terms from time to time; if we make material changes, we will provide
            reasonable notice, such as by updating the &ldquo;Last updated&rdquo; date above or
            notifying you directly. Continued use of the Service after changes take effect
            constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="12. Governing Law and Disputes">
          <p>
            These Terms are governed by the laws of the State of Delaware, without regard to its
            conflict-of-laws principles. Any dispute arising out of or relating to these Terms or
            the Service shall be resolved through binding individual arbitration, and you waive any
            right to participate in a class action or class arbitration.
          </p>
        </Section>

        <Section title="13. General">
          <p>
            If any provision of these Terms is found unenforceable, the remaining provisions will
            remain in full effect. Our failure to enforce any right or provision is not a waiver of
            that right. These Terms constitute the entire agreement between you and Clario
            regarding the Service.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms can be sent to{" "}
            <a href="mailto:legal@clario.app" className="text-primary-700 hover:underline">
              legal@clario.app
            </a>
            .
          </p>
        </Section>
      </main>
    </div>
  )
}
